name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ '*' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node
      uses: actions/setup-node@v1
    - name: Install mocha
      run: npm install -g mocha
    - name: Install dependencies
      run: npm install 
    - name: "Run Test"
      run: mocha ./src/test/unit/index.test.js

  auto-tag:
    needs: [unit-test]
    runs-on: ubuntu-latest
    steps:
    - name: Auto tag version
    - uses: actions/checkout@v2
    - uses: butlerlogic/action-autotag@stable
      with:
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        tag_prefix: 'v'

  CI-success:
    needs: [auto-tag]
    runs-on: ubuntu-latest
    steps:
    - name: CI success
      run: |
        echo CI success.
