name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ '*' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  CI-start:
    runs-on: ubuntu-latest
    steps:
    - name: CI starting
      run: |
        echo CI-starting

  unit-test:
    needs: [CI-start]
    runs-on: ubuntu-latest
    steps:
    - name: Run-unit-tests-11
      uses: ${{ github.repository }}/Unit tests
#       uses: peter-evans/repository-dispatch@v1
#       with:
#         token: ${{ secrets.FRAMEBOT_CI_TOKEN }}
#         repository: ${{ github.repository }}
#         event-type: Unit-tests
#         client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

  auto-tag:
    needs: [unit-test]
    runs-on: ubuntu-latest
    steps:
    - name: Auto-tag-11
      if: success()
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.FRAMEBOT_CI_TOKEN }}
        repository: ${{ github.repository }}
        event-type: Auto-tag
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

  CI-success:
    needs: [auto-tag]
    runs-on: ubuntu-latest
    steps:
    - name: CI success
      run: |
        echo CI success.
